### ISSUE TITLE
Caverunner license

### ISSUE THREAD

**Issue by gergoerdi** [simonmichael/games#1]
The `ansi-terminal-game` dependency is licensed under the GPLv3. IIUC, this means that `caverunner` cannot, in general, be distributed under the terms of its own BSD license; in particular, if someone were to follow the BSD license to distribute a binary-only build of `caverunner`, they would be in violation of the license of `ansi-terminal-game`.

**Comment by simonmichael** [comment]
Fixed, thanks for reporting.
